CREATE TABLE "GCG_6063_PL_CAT"(
 "CATEGORY" CHAR(20),
 "PRODUCT_LINE" CHAR(2) NOT NULL,"Color" Varchar(50) );

CREATE UNIQUE INDEX "GCG_6063_I1" USING 0 ON "GCG_6063_PL_CAT"("CATEGORY", "PRODUCT_LINE");